export const home = "home"
export const cave = "The-Cave"
export const noodles = "n00dles"
export const foodnstuff = "foodnstuff"
export const defaultServerFortifyAmount = 0.002 // Mined from code
export const defaultServerWeakenAmount = 0.05 // Mined from code
export const homeReservedRam = 128
export const thisScript = "timeburn.js"
export const baseRamCost = 1.6 // Mined from code, better to hardcode this than the spit a empty file and get the RAM cost of it...
